import './globals.css';
import { Poppins, Roboto } from 'next/font/google';
import { AOSInit } from '@/AOSInit';
import { ClerkProvider } from '@clerk/nextjs';
import PageLayout from '@/components/Layout';
import FacebookPixel from '@/components/FacebookPixel';
import Analytics from '@/components/Analytics';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
  weight: ['100', '300', '400', '500', '700', '900'],
});

export const metadata = {
  title: 'ZYVO | Hourly spaces',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <AOSInit />
      <html lang='en'>
        <body className={`${roboto.className} ${poppins.className} `}>
          {/* Global Site Tag (gtag.js) - Google Analytics */}
          <script
            async
            src={`https://www.googletagmanager.com/gtag/js?id=AW-11436521193`}
          />
          <script
            dangerouslySetInnerHTML={{
              __html: `
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                gtag('config', 'AW-11436521193');
              `,
            }}
          />
          <Analytics />
          <PageLayout>{children}</PageLayout>
          <FacebookPixel />
        </body>
      </html>
    </ClerkProvider>
  );
}
